version: '3'

services:

  flask:
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      DATABASE_USER: admin
      DATABASE_PASSWORD: pass
      DATABASE_HOST: db
      DATABASE_NAME: db
      YOUR_CHANNEL_ACCESS_TOKEN: yeEN+/lLxR7zur1WDDTB1RrB3+UR8uXaYhAZNR10KCn3fS61nhAUPRzkVfx3SWbfq3Qm198d78DSypkALK+HRobiDZU4Tpngxio/ie4J/Z6LX0vABeKpX1gPgCg+e2+Dv38oJ3gsCqgd1MTOXXb18wdB04t89/1O/w1cDnyilFU=
      YOUR_CHANNEL_SECRET: dcffcbcc2054eaa4c4abb2231eb3a134
      FLASK_APP: __init__.py
      APP_ENV: development
      SLACK_WEBHOOK: https://hooks.slack.com/services/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
      SLACK_CHANNEL: '#そてそてすずめ_notify'
      SLACK_ICON: https://avatars.slack-edge.com/2021-03-10/1848451967060_13a50ec1f6494a50b368_48.jpg
    volumes:
      - ./src:/var/app/src
    depends_on:
      - db

  schedule:
    build:
      context: .
      dockerfile: Dockerfile_schedule
    restart: always
    environment:
      DATABASE_USER: admin
      DATABASE_PASSWORD: pass
      DATABASE_HOST: db
      DATABASE_NAME: db
      YOUR_CHANNEL_ACCESS_TOKEN: yeEN+/lLxR7zur1WDDTB1RrB3+UR8uXaYhAZNR10KCn3fS61nhAUPRzkVfx3SWbfq3Qm198d78DSypkALK+HRobiDZU4Tpngxio/ie4J/Z6LX0vABeKpX1gPgCg+e2+Dv38oJ3gsCqgd1MTOXXb18wdB04t89/1O/w1cDnyilFU=
      YOUR_CHANNEL_SECRET: dcffcbcc2054eaa4c4abb2231eb3a134
      FLASK_APP: __init__.py
      APP_ENV: development
      SLACK_WEBHOOK: https://hooks.slack.com/services/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
      SLACK_CHANNEL: '#そてそてすずめ_notify'
      SLACK_ICON: https://avatars.slack-edge.com/2021-03-10/1848451967060_13a50ec1f6494a50b368_48.jpg
    volumes:
      - ./src:/var/app/src
    depends_on:
      - flask

  db:
    build:
      context: postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pass
    volumes:
      - ./postgres/db_data:/var/lib/postgresql/data

volumes:
  src: {}
  db_data: {}
